### ISSUE TITLE
YouTube Updated their website again, so Extension is broke

### ISSUE THREAD

**Issue by Scotty-Trees** [ProbablyRaging/hide-youtube-shorts#13]
### Describe the issue

Greetings,

Figured I'd file a bug report here than post a comment on Chrome Extensions web store to help out. Looks like YouTube recently updated some of their pages, i.e. the Subscription page now has large thumbnails instead of the more traditional smaller ones and as such that recent change has now caused the Hide Shorts extension to no longer work.

Hopefully it's an easy enough fix, but just thought I should let you know. Good luck, keep up the good work, and thanks for making this wonderful extension. 

### What version of HYS are you using?

Hide YouTube Shorts version 1.5.0

### What browsers are you seeing the problem on?

Vivaldi version 6.0.2979.25

### Latest browser version?

Yes

Edit: I see you just released v1.6.0, not sure if that will fix this issue, but I will let you know when Chrome Web Store updates it, probably within a couple hours.

**Comment by zevnda** [comment]
Thanks for the heads up. It would appear that YouTube are still rolling out treatments with this new UI. One of my accounts now has it _(finally able to do some proper testing myself)_, while one of my alts does not.

The good news is that I was able to push a quick update just now, which should solve the issues with Shorts not being hidden on the subscriptions page on the new UI.

The bad news is that the new UI now displays videos in rows of 4 items _(depending on screen size)_ down the page. The issue here is that previously, when a video was hidden/removed, another video would take its place without leaving a gap. However, now it leaves a gap.

I tried a few different methods, such as moving all the children of each row to a custom flex div, but this would be too resource-intensive, especially for users with lower-end systems. I might need to revisit this in the future, but for now, people will have to deal with the gaps left behind by Shorts elements. 😂

Regarding your edit, version 1.6.0 does not contain any fixes for the new UI. Unfortunately, I only got access to the new UI about an hour or two after I submitted that version to CWS for review. Version 1.6.1 will contain the fixes, but it will likely be delayed by a day or two.

Let me know if you come across any other issues with the new UI.

Thanks again, and I'm glad you've found usefulness in the extension 👍🏼

**Comment by zevnda** [comment]
Fixed in 1.6.1 with [d8eda0e](https://github.com/ProbablyRaging/hide-youtube-shorts/commit/d8eda0e0b488fd0d5d2f3ba65244bc0e6df7acd6)

You can download the .zip from this repo and load the unpacked version or give it a couple of days to go live on CWS. 

Feel free to open a new issue if you have any more problems with the new UI

**Comment by Scotty-Trees** [comment]
Thanks mate, appreciate the quick update! I'll see how it goes the next week or two and see if YouTube pushes out any more UI tweaks. Personally I am not a fan of the new giant sized thumbnails now in Subscriptions. I much prefer being able to see ~24 videos tiles a quick glance to choose from without having to scroll. Now I'm lucky to even see 8 video [big] thumbnails at best with the new redesign. Not a fan at all, but I digress lol. 

Old Layout {RIP}
![Screenshot from 2022-05-26 13-19-05](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/45135187/ab0ef5fe-3612-47c3-ab37-085cceb0097d)

New Layout
![Screenshot from 2023-06-06 18-33-04](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/45135187/98afe284-5678-444a-827c-6f184267778c)
