### ISSUE TITLE
Why does the extension request to read my browsing history?

### ISSUE THREAD

**Issue by Sparktion** [ProbablyRaging/hide-youtube-shorts#22]
### Describe the issue

See title, I do not understand why this extension should view browsing history.

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Chrome

### Latest browser version?

Yes

**Comment by zevnda** [comment]
Thank you for opening a ticket.

Yes, these new permission changes have been reverted in version `1.6.14` with afc413e290bab2262d16441cbffe574b4f1acd29.

The update should be live on the Chrom Web Store within 24 hours.

If you are concerned about the permission, you can disable/uninstall the extension temporarily until the new update is live. I will make an announcement on our Discord once the new update is live here https://discord.com/invite/HAFP4P7Dfr

**Comment by Sparktion** [comment]
Is there a reason for this change?

**Comment by zevnda** [comment]
> Is there a reason for this change?

There was yes. I opted to change the method of hiding shorts from using JS to CSS for performance reason, you can read more about those changes here https://github.com/ProbablyRaging/hide-youtube-shorts/releases/tag/1.6.13

The changes required a new permission, the permissions in question is the `tabs` permission which gives access to the `chrome.tabs` API, specifically I needed its `url` property. You can read more about that here (https://developer.chrome.com/docs/extensions/reference/tabs/#perms).

I opted to use the `url` property because it would give the extensions better control over which pages it was inserting CSS on. 

An example of this would be only inserting 2 lines of CSS that would hide certain elements on the `https://youtube.com/feed/subscriptions` page, rather then inserting about 20 lines of CSS on all pages, which would effectively break the page entirely. 

The extension having access to the current url of the tab is what is considered `reading browser history`.

Though, as mentioned, I have decided to rollback this update before the introduction of this new permission in `1.6.14` with afc413e290bab2262d16441cbffe574b4f1acd29 and that update should be live on CWS within 24 hours.

**Comment by Wright4i** [comment]
FWIW the implementation doesn't look malicious and indeed the UX is significantly improved in 1.6.13, but yeah that's a scary pop-up to get for the end user. That's a lot of work to revert, but I think it was the right call.

**Comment by zevnda** [comment]
> FWIW the implementation doesn't look malicious and indeed the UX is significantly improved in 1.6.13, but yeah that's a scary pop-up to get for the end user. That's a lot of work to revert, but I think it was the right call.

Oh 100% agree with you there. If I knew that the permission was that intrusive I would never have implemented it in the first place. Unfortunately the documentation regarding it does not mention anything about just how intrusive it is, and only that it gives access to "four sensitive properties on `tabs.Tab` instances: `url`, `pendingUrl`, `title`, and `favIconUrl`"

The warning however makes it sounds like I was able to access every little bit of the users browser data or something, which I most definitely wasn't able to lol and nor would I want to.

Definitely happy to revert those changes for sure! Thank you for taking the time to review it 👍🏼 

But yeah, I'm fully for open-source code for this reason exactly. Anyone is able to come and review it and see that there was absolutely no malicious intent what-so-ever.

**Comment by Wright4i** [comment]
You definitely aren't the first to be caught off-guard by `tabs`. I'd love to see a restricted version of `tabs` that let you guess the current URL and it only returned true/false if you were right. That way you couldn't just access the full url at all times. That would certainly improve security and maybe wouldn't set off so many red flags 🚩

**Comment by zevnda** [comment]
That definitely sounds like a much less intrusive approach for sure. Maybe we'll see some changes in manifest v4, who knows.

I'll leave this issue open for the time being, incase anyone else comes along looking for the same answers.

Thanks again!

**Comment by zevnda** [comment]
`1.6.14` is not live and available for download/update on the Chrome Web Store.
