### ISSUE TITLE
Extension requests new permissions: read/write to all sites 

### ISSUE THREAD

**Issue by timmeinerzhagen** [ProbablyRaging/hide-youtube-shorts#24]
Starting with the `1.6.15` version, the extension is asking for read/write permissions to all sites instead of just `https://www.youtube.com` and `https://m.youtube.com` as it was before.

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/34220101/76f04e8a-a22a-4f24-a99a-7b86f02acace)

This change seems to have come from the latest commit [`Merged changes from the beta branch`](https://github.com/ProbablyRaging/hide-youtube-shorts/commit/1381626f7fbfc5576456c817410ca3f6f426573f). See [direct link to change diff](https://github.com/ProbablyRaging/hide-youtube-shorts/commit/1381626f7fbfc5576456c817410ca3f6f426573f?diff=unified#diff-639916bc14c3f311c31f629a2ec116292a4b2f64d06b3607b9ddd2e495703895L9-L12).

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/34220101/3548917b-1fba-4755-a808-69910b3bb116)

Were these requested permissions intentional? Or was a testing change for the beta branch that was adopted to main by mistake? I don't see the need for the permissions.

Or is this a second iteration on https://github.com/ProbablyRaging/hide-youtube-shorts/issues/22#issuecomment-1596299327? This permission request does not seem much better ;)

**Comment by zevnda** [comment]
Thank for checking in, these changes are indeed intentional.

I've changed the way I declare hosts, instead of declaring just the previous youtube domains, I've opted to delcare `<all_urls>` in order for the recent changes to work correctly without the intrusive `reads browsing history` warning. The changes in question are the use of `insertCSS()` and `executeScript()` methods.

### If you want to manually limit which sites the extension can access; 
- Go to `chrome://extensions` _(or manage extensions)_
- Select `Details` on the extension
- Under `Site access` you can allow the extension to only work on specific sites. Make sure it works on `www.youtube.com` and `m.youtube.com` if you use HYS on mobile browser.

These changes will stay, as I believe this provides a better user experience overall

**Comment by timmeinerzhagen** [comment]
Thanks for the prompt response! Makes perfect sense.

With the manual limit of the pages scope it seems better to me, though it is a bit scary when a "simple" app that supposedly should not need it asks for broad access outside of its supposed applicable site or wants access to browser history. I'm sure that will turn away some users that don't want to spend time checking out the code. 

Also even if you don't intend to misuse this access, I don't love this opening up a possible avenue for a malicous attacker. If they were successful in taking over this repo, they could easily insert malicous code that actually misuse those permission in the user's browser. All that just gets rolled out via the extension auto-update, since you already got those permissions. 

But I suppose there is not much to do about that with Google's shitty naming and permission scopes for ya.

> I've opted to delcare <all_urls> in order for the recent changes to work correctly without the intrusive `reads browsing history warning`

Are you sure changing that warning worked out? I uninstalled and reinstalled the extension and it still discloses that it uses that permission in the extension settings. The initial extension installation now just says `Read and change all your data on all websites` which - as I said - is probably not much better either.

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/34220101/2ece864d-2a93-4c81-b6a2-04396a233cde)

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/34220101/31e490ee-1987-4229-a67c-749bc6c3e183)

> These changes will stay, as I believe this provides a better user experience overall

It is actually noticably faster with the CSS which is amazing, so I like the change overall, but the extension permission stuff still seems like a pain.

Thank you for looking to improve the user experience despite the roadblocks that Google seems to have invented for you!

**Comment by zevnda** [comment]
Yeah at that point we can only really rely on Google's auditing proccess that they do on extensions, that audit happens for every update made to the extension by the way. Google keeps a pretty tight lid over its official store, with any "dangerous" APIs behind permissions and the code audited (not by humans) for malicious patterns. 

They won't even approve an extension if they believe it's permissions are outside of the "single-purpose"
**https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#best-practices**
> Request relevant permissions
Extensions are required to fulfill a [single purpose](https://developer.chrome.com/docs/extensions/mv3/single_purpose/) and comply with the [Use of permissions](https://developer.chrome.com/docs/webstore/program-policies/permissions/) policy. Ensure you only request permissions that support the extension's main functionality.

If Google can't see anything suspicions before they allow it to go live, there's very little hope we have for seeing anything suspicious in an application.

Hopefully Google offers us some better scoped permissions in future versions of the API 🤞

**Comment by dominic-schmid** [comment]
I don't have anything meaningful to contribute to this discussion so feel free to delete my comment but I wanted to reaffirm

>  I'm sure that will turn away some users that don't want to spend time checking out the code.

After the last update asking for browser history, I uninstalled the extension immediately. Since shorts are **really** quite something, I reluctantly reinstalled it, but with this new update I had the same original reaction, again.

I understand the Chrome API just doesn't offer the needed functionality with other permissions and am thankful for open source but it might make sense to specifically mention this issue for users.

**Comment by mniborsk** [comment]
Hi there, just seconding @timmeinerzhagen's comment that the `Read your browsing history` permission is still appearing in v1.6.15.

**Comment by solarisfire** [comment]
Why on earth does this need access to all sites and not just youtube?? I don't get it...

**Comment by bk7312** [comment]
> > I've opted to delcare <all_urls> in order for the recent changes to work correctly without the intrusive `reads browsing history` warning
> 
> Are you sure changing that warning worked out? I uninstalled and reinstalled the extension and it still discloses that it uses that permission in the extension settings. 

The intrusive `reads browsing history` warning is gone but the `Read your browsing history` permission is still there, probably because `chrome.tabs` is still being used.

Looking at the docs, I thought using the `activeTab` permission would solve everything, but it's actually quite limiting and requires user action to activate. Not sure what else can be done aside from us manually limiting site access.

**Comment by zevnda** [comment]
> I understand the Chrome API just doesn't offer the needed functionality with other permissions and am thankful for open source but it might make sense to specifically mention this issue for users.

Yeah unfortunately people who are quick to assume to worst, and those people are likely not going to take the time to read the API documentation _(and likely aren't just going to just take my word for it)_.

At the end of the day, I made this extension as a personal project and even with its growing popularity it will still remain a personal project. I followed Google's permission guidelines as best I could, and I got my desired outcome in terms of how the extension functions.

People are welcome to not use the extension if they feel some kind of way about it.

**Comment by wiretail** [comment]
It's also why I try to only use extensions that have a public repo with discussion and (more) eyeballs on it.  When I saw the permission request, I first came here, read this issue, looked at the code...and cool.

**Comment by zevnda** [comment]
> It's also why I try to only use extensions that have a public repo with discussion and (more) eyeballs on it. When I saw the permission request, I first came here, read this issue, looked at the code...and cool.

I appreciate you taking the time to come review the code yourself mate! Thank you!

**Comment by ZoinkersCrikey** [comment]
This extension is useful and works great.
IMO what is relevant about the permissions is if they can be used maliciously and the answer is YES. 
Therefore we come to a situation that all that matters is Trust.
No one individual should ask to be trusted. It's impossible to give said trust and be safe.
A version without having to trust would be great, even if its performance is slower. Till then I shall have to hide mah shorts in some other manner.

PS: I thank you for your efforts on providing users with this functionality, those damned shorts are utterly annoying, so please don't take the lack of trust to mean we don't value your work.

**Comment by zevnda** [comment]
> This extension is useful and works great. IMO what is relevant about the permissions is if they can be used maliciously and the answer is YES. Therefore we come to a situation that all that matters is Trust. No one individual should ask to be trusted. It's impossible to give said trust and be safe. A version without having to trust would be great, even if its performance is slower. Till then I shall have to hide mah shorts in some other manner.
> 
> PS: I thank you for your efforts on providing users with this functionality, those damned shorts are utterly annoying, so please don't take the lack of trust to mean we don't value your work.

While I agree with you somewhat, I can't agree completely.

I agree that a level of trust and transparency should be maintained by the developers, which I believe I offer by leaving this project open-source and by using common permissions which follow Google's policies as I mentioned previously. I also believe I have created the extension in such a way that it creates a good user experience with the least intrusive permissions that I can with tools available to me, provided by Google.

After that point _(when the extension is uploaded to the Chrome Web Store)_, it is up to Google to audit the extension to make sure it does nothing that they would consider malicious or outside the scope of what they call an extension's "single-purpose." Which it does not; otherwise, it would not be live on the CWS right now, and it would not have the badges that it does.

From there, the responsibility falls onto the user in a few ways:
- They can review the permissions being used before installing.
- They can limit the extension's access after installing. _(an extension can only access what the user allows it to access)_
- They can review the changed permissions before re-enabling the extension if it was already previously installed.
- They can do their own research on what these permissions can actually do/access.
- They can choose to uninstall the extension.

I fully understand that not everyone is able to or willing to do some of the above, and that is totally fine. No one is forced to use the extension, and they are welcome to their opinion about these changes, though when reviewing the extension's analytics I'm seeing that they are the vocal minority and definitely not the majority.

Keep in mind that this extension is still relatively new and actively being developed, so changes are imminent. I also believe these changes have created a better user experience and have improved the code's overall readability and maintainability _(pretty important for a single dev project that needs to work for a site that changes frequently and usually without warning)_.

I'm definitely not discouraged by this at all, if anything, quite the opposite. Makes me realize that people did, and mostly still do find this to be quite a useful extension, and it gives me the motivation to continue improving and maintaining it.

Thank you for your input 🍻
