### ISSUE TITLE
Future Firefox extension

### ISSUE THREAD

**Issue by curiousdreamer** [ProbablyRaging/hide-youtube-shorts#28]
### Describe the feature

This would be especially nice because of the fact that you can hide shorts tabs on individual channels, which I have not seen on other extensions as far as I know. Also doesn't seem to break as often from what I tested.

**Comment by zevnda** [comment]
Appreciate the suggestion!

I have considered porting the extension to firefox but I'm a little hesitant as I'm not all that familiar with the Firefox extension API and what differs between it and the Chrome extension API, also because this is a single dev project and I'm not sure I'd actually have the time to keep both versions of the extension updated unfortunately.

However, if anyone would like to take on the chore of porting this to Firefox, they are more than welcome to get in contact with me to discuss.
