### ISSUE TITLE
Other websites/services affected by extension

### ISSUE THREAD

**Issue by SirSerpentius** [ProbablyRaging/hide-youtube-shorts#8]
### Describe the issue

Other websites and services cease to function properly while extension is enabled.
Using the Chrome browser on a Windows 10 desktop machine.

When visiting Disney + streaming service, playing any video fails after the video is selected.
When I turn off the Hide YouTube shorts extension, the video plays just fine as normal.
If I re-enable or turn back on the Hide YouTube shorts extension, the videos fail to play again and the site is rendered unusable.
I have also experienced other sites that require pop ups or verification stop functioning normally when this extension is enabled.

Happy to provide additional information to assist in troubleshooting as I really appreciate this extension.

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Chrome

### Latest browser version?

- [X] Yes

**Comment by zevnda** [comment]
I really have no idea how this could be possible as the extension can only interact with `youtube.com` pages as shown below.

https://github.com/ProbablyRaging/hide-youtube-shorts/blob/59e644b8e60dc5b428c4d9ccacd224406c00300b/manifest.json#L9-L12

As the extension currently is, I see no possible way the extension could interfere with the Disney+ site in a way that I can easily determine and fix.

The only thing I can think that might cause this issue is the fact that most subscription-based OTT streaming providers such as Disney+, Netflix, and Hulu have measures to prevent copyright infringement and it may very well see HYS as some sort of threat, though I highly doubt it. I personally don't use Disney+ but I use a few different streaming providers and I have not had any issues with the extension interfering with them.

If this turns out to be a more widespread issue than just yourself, I may look into it a little more, but as of right now, I can't see this being a common issue.
